---
collections:
  - name: cisco.ios
    version: 0.0.2
    source: https://galaxy.ansible.com
  - name: cisco.asa
    version: 0.0.1
    source: https://galaxy.ansible.com
  - name: cisco.nxos
    version: 0.0.2
    source: https://galaxy.ansible.com
  - name: cisco.iosxr
    version: 0.0.2
    source: https://galaxy.ansible.com
roles:
  - name: securenetwrk.gold_config
